title: My CS 1030 Website
author: Logan Johnson
logo: /assets/img/logo.png
description: "This site highlights the work that I have done as part of my degree in Computer Science"
google_analytics:
theme: jekyll-theme-minimal
